/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTitikRouteImport } from './routes/admin.titik'
import { Route as AdminSesiRouteImport } from './routes/admin.sesi'
import { Route as AdminRiwayatRouteImport } from './routes/admin.riwayat'
import { Route as AdminPetaRouteImport } from './routes/admin.peta'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTitikRoute = AdminTitikRouteImport.update({
  id: '/titik',
  path: '/titik',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSesiRoute = AdminSesiRouteImport.update({
  id: '/sesi',
  path: '/sesi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiwayatRoute = AdminRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPetaRoute = AdminPetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/peta': typeof AdminPetaRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/sesi': typeof AdminSesiRoute
  '/admin/titik': typeof AdminTitikRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/peta': typeof AdminPetaRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/sesi': typeof AdminSesiRoute
  '/admin/titik': typeof AdminTitikRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/peta': typeof AdminPetaRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/sesi': typeof AdminSesiRoute
  '/admin/titik': typeof AdminTitikRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/peta'
    | '/admin/riwayat'
    | '/admin/sesi'
    | '/admin/titik'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/peta'
    | '/admin/riwayat'
    | '/admin/sesi'
    | '/admin/titik'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/peta'
    | '/admin/riwayat'
    | '/admin/sesi'
    | '/admin/titik'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/titik': {
      id: '/admin/titik'
      path: '/titik'
      fullPath: '/admin/titik'
      preLoaderRoute: typeof AdminTitikRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sesi': {
      id: '/admin/sesi'
      path: '/sesi'
      fullPath: '/admin/sesi'
      preLoaderRoute: typeof AdminSesiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riwayat': {
      id: '/admin/riwayat'
      path: '/riwayat'
      fullPath: '/admin/riwayat'
      preLoaderRoute: typeof AdminRiwayatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/peta': {
      id: '/admin/peta'
      path: '/peta'
      fullPath: '/admin/peta'
      preLoaderRoute: typeof AdminPetaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPetaRoute: typeof AdminPetaRoute
  AdminRiwayatRoute: typeof AdminRiwayatRoute
  AdminSesiRoute: typeof AdminSesiRoute
  AdminTitikRoute: typeof AdminTitikRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPetaRoute: AdminPetaRoute,
  AdminRiwayatRoute: AdminRiwayatRoute,
  AdminSesiRoute: AdminSesiRoute,
  AdminTitikRoute: AdminTitikRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
