/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetugasRouteImport } from './routes/petugas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetugasIndexRouteImport } from './routes/petugas.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PetugasScanRouteImport } from './routes/petugas.scan'
import { Route as AdminTitikRouteImport } from './routes/admin.titik'
import { Route as AdminSesiRouteImport } from './routes/admin.sesi'
import { Route as AdminRiwayatRouteImport } from './routes/admin.riwayat'
import { Route as AdminPetaRouteImport } from './routes/admin.peta'

const PetugasRoute = PetugasRouteImport.update({
  id: '/petugas',
  path: '/petugas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasIndexRoute = PetugasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetugasRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PetugasScanRoute = PetugasScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => PetugasRoute,
} as any)
const AdminTitikRoute = AdminTitikRouteImport.update({
  id: '/titik',
  path: '/titik',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSesiRoute = AdminSesiRouteImport.update({
  id: '/sesi',
  path: '/sesi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiwayatRoute = AdminRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPetaRoute = AdminPetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/petugas': typeof PetugasRouteWithChildren
  '/admin/peta': typeof AdminPetaRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/sesi': typeof AdminSesiRoute
  '/admin/titik': typeof AdminTitikRoute
  '/petugas/scan': typeof PetugasScanRoute
  '/admin/': typeof AdminIndexRoute
  '/petugas/': typeof PetugasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/peta': typeof AdminPetaRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/sesi': typeof AdminSesiRoute
  '/admin/titik': typeof AdminTitikRoute
  '/petugas/scan': typeof PetugasScanRoute
  '/admin': typeof AdminIndexRoute
  '/petugas': typeof PetugasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/petugas': typeof PetugasRouteWithChildren
  '/admin/peta': typeof AdminPetaRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/sesi': typeof AdminSesiRoute
  '/admin/titik': typeof AdminTitikRoute
  '/petugas/scan': typeof PetugasScanRoute
  '/admin/': typeof AdminIndexRoute
  '/petugas/': typeof PetugasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/petugas'
    | '/admin/peta'
    | '/admin/riwayat'
    | '/admin/sesi'
    | '/admin/titik'
    | '/petugas/scan'
    | '/admin/'
    | '/petugas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/peta'
    | '/admin/riwayat'
    | '/admin/sesi'
    | '/admin/titik'
    | '/petugas/scan'
    | '/admin'
    | '/petugas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/petugas'
    | '/admin/peta'
    | '/admin/riwayat'
    | '/admin/sesi'
    | '/admin/titik'
    | '/petugas/scan'
    | '/admin/'
    | '/petugas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PetugasRoute: typeof PetugasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/petugas': {
      id: '/petugas'
      path: '/petugas'
      fullPath: '/petugas'
      preLoaderRoute: typeof PetugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas/': {
      id: '/petugas/'
      path: '/'
      fullPath: '/petugas/'
      preLoaderRoute: typeof PetugasIndexRouteImport
      parentRoute: typeof PetugasRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/petugas/scan': {
      id: '/petugas/scan'
      path: '/scan'
      fullPath: '/petugas/scan'
      preLoaderRoute: typeof PetugasScanRouteImport
      parentRoute: typeof PetugasRoute
    }
    '/admin/titik': {
      id: '/admin/titik'
      path: '/titik'
      fullPath: '/admin/titik'
      preLoaderRoute: typeof AdminTitikRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sesi': {
      id: '/admin/sesi'
      path: '/sesi'
      fullPath: '/admin/sesi'
      preLoaderRoute: typeof AdminSesiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riwayat': {
      id: '/admin/riwayat'
      path: '/riwayat'
      fullPath: '/admin/riwayat'
      preLoaderRoute: typeof AdminRiwayatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/peta': {
      id: '/admin/peta'
      path: '/peta'
      fullPath: '/admin/peta'
      preLoaderRoute: typeof AdminPetaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPetaRoute: typeof AdminPetaRoute
  AdminRiwayatRoute: typeof AdminRiwayatRoute
  AdminSesiRoute: typeof AdminSesiRoute
  AdminTitikRoute: typeof AdminTitikRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPetaRoute: AdminPetaRoute,
  AdminRiwayatRoute: AdminRiwayatRoute,
  AdminSesiRoute: AdminSesiRoute,
  AdminTitikRoute: AdminTitikRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PetugasRouteChildren {
  PetugasScanRoute: typeof PetugasScanRoute
  PetugasIndexRoute: typeof PetugasIndexRoute
}

const PetugasRouteChildren: PetugasRouteChildren = {
  PetugasScanRoute: PetugasScanRoute,
  PetugasIndexRoute: PetugasIndexRoute,
}

const PetugasRouteWithChildren =
  PetugasRoute._addFileChildren(PetugasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PetugasRoute: PetugasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
